project:
  type: website
  output-dir: docs

website:
  title: "Claire To"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd

format:
  html:
    theme:
      - minty
      - custom.scss
    css: styles.css
    toc: true



